version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"  # Порт для серверу
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"  # Порт для React клієнта
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
