version: '3.8'

services:
  client:
    build:
      context: ./client  # Шлях до клієнтського Dockerfile
    ports:
      - "3000:3000"  # Проксіюємо порт 3000 хоста на контейнер
    depends_on:
      - server  # Запускаємо клієнт тільки після сервера
    environment:
      - NODE_ENV=production

  server:
    build:
      context: ./server  # Шлях до серверного Dockerfile
    ports:
      - "5000:5000"  # Проксіюємо порт 5000 хоста на контейнер
    environment:
      - NODE_ENV=production
