version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # 1) Ваш бекенд
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  # 2) Контейнер з клієнтом (serve build/)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - server        # щоб спочатку бекенд піднявся, якщо вам важливо
    networks:
      - app-network

  # 3) Nginx-проксі
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - client
      - server
    ports:
      - "80:80"
      - "443:443"   # для HTTPS
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # сертифікати можна змонтувати сюди пізніше:
      # - ./docker/nginx/certs:/etc/nginx/certs:ro
    networks:
      - app-network
