

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: $DOCKER_USERNAME/project2025-client:latest  # Додаємо тег для Docker Hub
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_ENV=production

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: $DOCKER_USERNAME/project2025-server:latest  # Додаємо тег для Docker Hub
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${DB_LINK}