version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  client-builder:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: builder
    # коли контейнер стартить, він просто миттєво завершиться (exit 0),
    # але volume client_build вже міститиме зібрану статику
    command: ["sh", "-c", "echo Static built; exit 0"]
    volumes:
      - client_build:/app/build
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - client-builder
      - server
    ports:
      - "80:80"
      - "443:443"    # з часом сюди заведете сертифікати
    volumes:
      - client_build:/usr/share/nginx/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # в майбутньому сюди можна монтувати ваші certs:
      # - ./docker/nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      # - ./docker/nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 5
    networks:
      - app-network

volumes:
  pg_data:
  client_build:
