version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - server
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - client
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/project-2025.ddns.net/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/project-2025.ddns.net/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    networks:
      - app-network
